version: '3.7'

services:
  pg:
    image: postgres
    volumes:
      - ./tmp/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
